/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 */
package Views;

import Classes.*;
import Exceptions.FuncionarioInexistenteException;
import Exceptions.FuncionarioJaExisteException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class AlterarFuncionario extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    boolean liberado = false;
    /**
     * Creates new form ListaFuncionario
     */
    public AlterarFuncionario(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idBuscaTxt = new javax.swing.JTextField();
        telefoneTxt = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nascimentoTxt = new javax.swing.JTextField();
        cpfTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        generoCombo = new javax.swing.JComboBox<>();
        emailTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rgTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dddTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        logradouroTxt = new javax.swing.JTextField();
        bairroTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cepTxt = new javax.swing.JTextField();
        numeroEnderecoTxt = new javax.swing.JTextField();
        cidadeTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        estadoCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pagamentoTxt = new javax.swing.JTextField();
        alterarButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar Funcionário");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idBuscaTxt.setForeground(new java.awt.Color(0, 0, 0));
        idBuscaTxt.setToolTipText("Insira o ID");
        idBuscaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idBuscaTxtKeyPressed(evt);
            }
        });
        getContentPane().add(idBuscaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 331, -1));

        telefoneTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(telefoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 125, -1));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 130, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        nomeTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 345, -1));

        jLabel8.setText("Data de nascimento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        nascimentoTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nascimentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 150, -1));

        cpfTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cpfTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 170, -1));

        jLabel9.setText("Genero");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        generoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        getContentPane().add(generoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 162, 30));

        emailTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 345, -1));

        jLabel5.setText("RG");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        rgTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(rgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 170, -1));

        jLabel6.setText("DDD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        dddTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(dddTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 27, -1));

        jLabel10.setText("Logradouro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        logradouroTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(logradouroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 345, -1));

        bairroTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(bairroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 170, -1));

        jLabel11.setText("Bairro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jLabel12.setText("Numero");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        cepTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cepTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 140, -1));

        numeroEnderecoTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numeroEnderecoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 170, -1));

        cidadeTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cidadeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 140, -1));

        jLabel15.setText("Cidade");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        estadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        getContentPane().add(estadoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 170, 30));

        jLabel16.setText("Estado");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel17.setText("CEP");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel18.setText("ID");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 180, -1));

        jLabel19.setText("Tipo");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        tipoTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 140, -1));

        jLabel20.setText("Pagamento");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        pagamentoTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(pagamentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 170, -1));

        alterarButton.setBackground(new java.awt.Color(255, 0, 51));
        alterarButton.setForeground(new java.awt.Color(255, 255, 255));
        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alterarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 100, -1));

        jLabel13.setText("Informe o ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 570));

        setBounds(170, 50, 694, 599);
    }// </editor-fold>//GEN-END:initComponents

    private void idBuscaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idBuscaTxtKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.buscarButton.doClick();
         }
    }//GEN-LAST:event_idBuscaTxtKeyPressed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        try{
            Funcionario i = sys.buscarFuncionario(idBuscaTxt.getText());
            nomeTxt.setText(i.getNome());
            cpfTxt.setText(i.getCpf());
            emailTxt.setText(i.getEmail());
            rgTxt.setText(i.getRg());
            dddTxt.setText(i.getTelefone().getDdd());
            telefoneTxt.setText(i.getTelefone().getNumero());
            nascimentoTxt.setText(i.getDataNascimento());
            generoCombo.setSelectedItem(i.getGenero());
            Endereco end = i.getEndereco();
            logradouroTxt.setText(end.getLogradouro());
            bairroTxt.setText(end.getBairro());
            cepTxt.setText(end.getCep());
            numeroEnderecoTxt.setText(end.getNumero());
            estadoCombo.setSelectedItem(end.getEstado());
            cidadeTxt.setText(end.getCidade());
            tipoTxt.setText(i.getTipo());
            idTxt.setText(i.getId());
            pagamentoTxt.setText(String.valueOf(i.getPagamento()));
            liberado = true;
            
        }catch(FuncionarioInexistenteException e){
            nomeTxt.setText("");
            cpfTxt.setText("");
            emailTxt.setText("");
            rgTxt.setText("");
            dddTxt.setText("");
            telefoneTxt.setText("");
            nascimentoTxt.setText("");
            generoCombo.setSelectedIndex(0);
            logradouroTxt.setText("");
            bairroTxt.setText("");
            cepTxt.setText("");
            numeroEnderecoTxt.setText("");
            estadoCombo.setSelectedIndex(0);
            cidadeTxt.setText("");
            tipoTxt.setText("");
            idTxt.setText("");
            pagamentoTxt.setText("");
            JOptionPane.showMessageDialog(this, e.getMessage());
            liberado = false;
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        if(liberado){
            try{
                ArrayList<String> campos = new ArrayList<>();
                
                Funcionario fun = sys.buscarFuncionario(idBuscaTxt.getText());
                fun.setDataNascimento(nascimentoTxt.getText());
                fun.setEmail(emailTxt.getText());
                Endereco end = new Endereco();
                end.setBairro(bairroTxt.getText());
                end.setCep(cepTxt.getText());
                end.setCidade(cidadeTxt.getText());
                end.setEstado(estadoCombo.getItemAt(estadoCombo.getSelectedIndex()));
                end.setLogradouro(logradouroTxt.getText());
                end.setNumero(numeroEnderecoTxt.getText());
                fun.setEndereco(end);
                fun.setGenero(generoCombo.getItemAt(generoCombo.getSelectedIndex()));
                fun.setNome(nomeTxt.getText());
                fun.setTipo(tipoTxt.getText());
                Telefone tel = new Telefone();
                tel.setDdd(dddTxt.getText());
                tel.setNumero(telefoneTxt.getText());
                fun.setTelefone(tel);
                boolean naoPassou = false;
                try{
                    Long.parseLong(cpfTxt.getText());
                    fun.setCpf(cpfTxt.getText());
                }catch (NumberFormatException e){
                    naoPassou = true;
                    campos.add("CPF");
                }
                try{
                    Long.parseLong(rgTxt.getText());
                    fun.setRg(rgTxt.getText());
                }catch(NumberFormatException e){
                    naoPassou = true;
                    campos.add("RG");
                }
                try{
                    fun.setPagamento(Double.parseDouble(pagamentoTxt.getText()));
                }catch(NumberFormatException e){
                    naoPassou = true;
                    campos.add("Pagamento");
                }
                
                fun.setId(idTxt.getText());
                
                if(!fun.getId().equals(idBuscaTxt.getText())){
                    try{
                        sys.cadastrarFuncionario(fun);
                        sys.removerFuncionario(idBuscaTxt.getText());
                    }catch(FuncionarioInexistenteException | FuncionarioJaExisteException e){
                        naoPassou = true;
                        campos.add("ID");
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                if(naoPassou){
                    JOptionPane.showMessageDialog(this, "Não foi possível alterar os seguintes campos: \n" + campos.toString());
                }else{
                    JOptionPane.showMessageDialog(this, "Funcionário alterado com sucesso!");
                }
                
            }catch(FuncionarioInexistenteException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Não foi possível alterar.");
        }
    }//GEN-LAST:event_alterarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JTextField bairroTxt;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField cepTxt;
    private javax.swing.JTextField cidadeTxt;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JTextField dddTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JComboBox<String> estadoCombo;
    private javax.swing.JComboBox<String> generoCombo;
    private javax.swing.JTextField idBuscaTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField logradouroTxt;
    private javax.swing.JTextField nascimentoTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField numeroEnderecoTxt;
    private javax.swing.JTextField pagamentoTxt;
    private javax.swing.JTextField rgTxt;
    private javax.swing.JTextField telefoneTxt;
    private javax.swing.JTextField tipoTxt;
    // End of variables declaration//GEN-END:variables
}
