/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 */
package Views;

import Classes.Instrumento;
import Classes.SistemaLojaMusical;
import Exceptions.InstrumentoInexistenteException;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class BuscarInstrumento extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form BuscarInstrumento
     */
    public BuscarInstrumento(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigoTxt = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        valorTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeTxt1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Instrumentos");
        getContentPane().setLayout(null);

        jLabel1.setText("código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(306, 55, 43, 17);

        jScrollPane1.setViewportView(codigoTxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(255, 82, 152, 26);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 240, 39, 17);

        nomeTxt.setEditable(false);
        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(180, 230, 354, 21);

        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 200, 39, 17);

        jLabel5.setText("Valor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 270, 44, 17);

        marcaTxt.setEditable(false);
        marcaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(marcaTxt);
        marcaTxt.setBounds(180, 190, 354, 21);

        buscarButton.setText("BUSCAR");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarButton);
        buscarButton.setBounds(270, 120, 120, 30);

        valorTxt.setEditable(false);
        valorTxt.setFocusable(false);
        valorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTxtActionPerformed(evt);
            }
        });
        getContentPane().add(valorTxt);
        valorTxt.setBounds(180, 270, 354, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 680, 440);

        nomeTxt1.setEditable(false);
        nomeTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTxt1);
        nomeTxt1.setBounds(180, 230, 354, 21);

        setBounds(170, 100, 675, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void marcaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTxtActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        try {
            Instrumento i = sys.buscarInstrumento(this.codigoTxt.getText());
            this.nomeTxt.setText(i.getNome());
            this.marcaTxt.setText(i.getMarca());
            valorTxt.setText(String.valueOf(i.getValor()));
        } catch (InstrumentoInexistenteException ex) {
            this.nomeTxt.setText("");
            this.marcaTxt.setText("");
            valorTxt.setText("");
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void nomeTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxt1ActionPerformed

    private void valorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextPane codigoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField nomeTxt1;
    private javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables
}
