package Views;

import Classes.Funcionario;
import Classes.SistemaLojaMusical;
import Exceptions.FuncionarioInexistenteException;

/**
 *
 * @author gustavo
 */
public class ListaDeFuncionarios extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form ListaDeFuncionarios
     */
    public ListaDeFuncionarios(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        rgTxt = new javax.swing.JTextField();
        cpfTxt = new javax.swing.JTextField();
        telefoneTxt = new javax.swing.JTextField();
        salarioTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista De Funcionarios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idCombo.addItem("Selecionar");
        for(String i: sys.idFuncionariosToStringArray()){
            idCombo.addItem(i);
        }
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });
        getContentPane().add(idCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 350, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 88, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("RG:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Salário:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));
        getContentPane().add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 350, -1));
        getContentPane().add(rgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 350, -1));
        getContentPane().add(cpfTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 350, -1));
        getContentPane().add(telefoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 350, -1));
        getContentPane().add(salarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 350, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        setBounds(150, 70, 754, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if(idCombo.getItemAt(idCombo.getSelectedIndex()).equals("Selecionar")){
            nomeTxt.setText("");
            rgTxt.setText("");
            cpfTxt.setText("");
            telefoneTxt.setText("");
            salarioTxt.setText("");
        }else{
            try{
                Funcionario fun = sys.buscarFuncionario(idCombo.getItemAt(idCombo.getSelectedIndex()));
                nomeTxt.setText(fun.getNome());
                rgTxt.setText(fun.getRg());
                cpfTxt.setText(fun.getCpf());
                telefoneTxt.setText(fun.getTelefone().toString());
                salarioTxt.setText(String.valueOf(fun.getPagamento()));
            }catch (FuncionarioInexistenteException e){
            }
        }
    }//GEN-LAST:event_idComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField rgTxt;
    private javax.swing.JTextField salarioTxt;
    private javax.swing.JTextField telefoneTxt;
    // End of variables declaration//GEN-END:variables
}
