package Views;

import Classes.Instrumento;
import Classes.SistemaLojaMusical;
import Exceptions.InstrumentoInexistenteException;

/**
 *
 * @author gustavo
 */
public class ListaDeInstrumentos extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form ListaDeInstrumentos
     */
    public ListaDeInstrumentos(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        qtdLabel = new javax.swing.JLabel();
        qtdTxt = new javax.swing.JTextField();
        valorTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JTextField();
        idCombo = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        nomeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomeLabel.setText("Nome:");

        marcaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marcaLabel.setText("Marca:");

        valorLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorLabel.setText("Valor:");

        qtdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        qtdLabel.setText("Quantidade:");

        qtdTxt.setEditable(false);

        valorTxt.setEditable(false);

        marcaTxt.setEditable(false);

        nomeTxt.setEditable(false);

        idCombo.addItem("Selecionar");

        for(String i: sys.idInstrumentosToStringArray()){
            idCombo.addItem(i);
        }
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLabel.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaLabel)
                            .addComponent(valorLabel)
                            .addComponent(qtdLabel))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtdTxt)
                            .addComponent(valorTxt)
                            .addComponent(marcaTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(idLabel))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorLabel)
                    .addComponent(valorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdLabel)
                    .addComponent(qtdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if(!idCombo.getSelectedItem().equals("Selecionar")){
            try{
                Instrumento ins = sys.buscarInstrumento(idCombo.getItemAt(idCombo.getSelectedIndex()));
                marcaTxt.setText(ins.getMarca());
                nomeTxt.setText(ins.getNome());
                valorTxt.setText(String.valueOf(ins.getValor()));
                qtdTxt.setText(String.valueOf(ins.getQuantidade()));
            }catch(InstrumentoInexistenteException e){  
            }
        }else {
                marcaTxt.setText("");
                nomeTxt.setText("");
                valorTxt.setText("");
                qtdTxt.setText("");
        }
    }//GEN-LAST:event_idComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel qtdLabel;
    private javax.swing.JTextField qtdTxt;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables
}
