/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 */
package Views;

import Classes.*;
import Exceptions.FuncionarioInexistenteException;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class ListaFuncionario extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form ListaFuncionario
     */
    public ListaFuncionario(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTxt = new javax.swing.JTextField();
        telefoneTxt = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nascimentoTxt = new javax.swing.JTextField();
        cpfTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        generoCombo = new javax.swing.JComboBox<>();
        emailTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rgTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dddTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista Funcionario");
        getContentPane().setLayout(null);

        idTxt.setForeground(new java.awt.Color(153, 153, 153));
        idTxt.setToolTipText("Insira o ID");
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });
        getContentPane().add(idTxt);
        idTxt.setBounds(177, 44, 331, 21);

        telefoneTxt.setEditable(false);
        telefoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneTxtActionPerformed(evt);
            }
        });
        getContentPane().add(telefoneTxt);
        telefoneTxt.setBounds(124, 351, 125, 21);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarButton);
        buscarButton.setBounds(280, 100, 130, 27);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 213, 36, 17);

        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(124, 331, 52, 17);

        nomeTxt.setEditable(false);
        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(82, 236, 345, 21);

        jLabel8.setText("Data de nascimento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(264, 331, 119, 17);

        jLabel3.setText("Cpf");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(439, 213, 21, 17);

        nascimentoTxt.setEditable(false);
        nascimentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nascimentoTxt);
        nascimentoTxt.setBounds(264, 351, 161, 21);

        cpfTxt.setEditable(false);
        cpfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtActionPerformed(evt);
            }
        });
        getContentPane().add(cpfTxt);
        cpfTxt.setBounds(439, 236, 170, 21);

        jLabel9.setText("Genero");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(444, 331, 43, 17);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 269, 34, 17);

        generoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino\t", "Feminino" }));
        generoCombo.setEnabled(false);
        getContentPane().add(generoCombo);
        generoCombo.setBounds(444, 351, 162, 30);

        emailTxt.setEditable(false);
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailTxt);
        emailTxt.setBounds(82, 292, 345, 21);

        jLabel5.setText("RG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 269, 17, 17);

        rgTxt.setEditable(false);
        rgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgTxtActionPerformed(evt);
            }
        });
        getContentPane().add(rgTxt);
        rgTxt.setBounds(440, 292, 170, 21);

        jLabel6.setText("DDD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(84, 331, 27, 17);

        dddTxt.setEditable(false);
        dddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddTxtActionPerformed(evt);
            }
        });
        getContentPane().add(dddTxt);
        dddTxt.setBounds(84, 351, 27, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 460);

        setBounds(170, 100, 694, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
        
    }//GEN-LAST:event_idTxtKeyPressed

    private void telefoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneTxtActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        try{
            Funcionario i = sys.buscarFuncionario(idTxt.getText());
            
            nomeTxt.setText(i.getNome());
            cpfTxt.setText(i.getCpf());
            emailTxt.setText(i.getEmail());
            rgTxt.setText(i.getRg());
            dddTxt.setText(i.getTelefone().getDdd());
            telefoneTxt.setText(i.getTelefone().getNumero());
            nascimentoTxt.setText(i.getDataNascimento());
            if(i.getGenero().startsWith("M")){
                generoCombo.setSelectedIndex(0);
            }else{
                generoCombo.setSelectedIndex(1);
            }
        }catch(FuncionarioInexistenteException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            nomeTxt.setText("");
            cpfTxt.setText("");
            emailTxt.setText("");
            rgTxt.setText("");
            dddTxt.setText("");
            telefoneTxt.setText("");
            nascimentoTxt.setText("");
            generoCombo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void nascimentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoTxtActionPerformed

    private void cpfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void rgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgTxtActionPerformed

    private void dddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dddTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JTextField dddTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JComboBox<String> generoCombo;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nascimentoTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField rgTxt;
    private javax.swing.JTextField telefoneTxt;
    // End of variables declaration//GEN-END:variables
}
