package Views;

import Classes.Instrumento;
import Classes.SistemaLojaMusical;
import Exceptions.InstrumentoInexistenteException;

/**
 *
 * @author gustavo
 */
public class ListaDeInstrumentos extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form ListaDeInstrumentos
     */
    public ListaDeInstrumentos(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        qtdLabel = new javax.swing.JLabel();
        qtdTxt = new javax.swing.JTextField();
        valorTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JTextField();
        idCombo = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Instrumentos");
        setName("Lista de Instrumentos"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomeLabel.setText("Nome:");
        getContentPane().add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        marcaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marcaLabel.setText("Marca:");
        getContentPane().add(marcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        valorLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorLabel.setText("Valor:");
        getContentPane().add(valorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        qtdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        qtdLabel.setText("Quantidade:");
        getContentPane().add(qtdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        qtdTxt.setEditable(false);
        getContentPane().add(qtdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 320, -1));

        valorTxt.setEditable(false);
        getContentPane().add(valorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 320, -1));

        marcaTxt.setEditable(false);
        getContentPane().add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 320, -1));

        nomeTxt.setEditable(false);
        getContentPane().add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 320, -1));

        idCombo.addItem("Selecionar");

        for(String i: sys.idInstrumentosToStringArray()){
            idCombo.addItem(i);
        }
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });
        getContentPane().add(idCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 320, -1));

        idLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLabel.setText("ID:");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 480));

        setBounds(170, 80, 701, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if(!idCombo.getSelectedItem().equals("Selecionar")){
            try{
                Instrumento ins = sys.buscarInstrumento(idCombo.getItemAt(idCombo.getSelectedIndex()));
                marcaTxt.setText(ins.getMarca());
                nomeTxt.setText(ins.getNome());
                valorTxt.setText(String.valueOf(ins.getValor()));
                qtdTxt.setText(String.valueOf(ins.getQuantidade()));
            }catch(InstrumentoInexistenteException e){  
            }
        }else {
                marcaTxt.setText("");
                nomeTxt.setText("");
                valorTxt.setText("");
                qtdTxt.setText("");
        }
    }//GEN-LAST:event_idComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel qtdLabel;
    private javax.swing.JTextField qtdTxt;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables
}
