package Views;

import Classes.Funcionario;
import Classes.SistemaLojaMusical;
import Exceptions.FuncionarioInexistenteException;
import Exceptions.PagamentoNaoAutorizadoException;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class RealizarPagamento extends javax.swing.JInternalFrame {

    SistemaLojaMusical sys;

    /**
     * Creates new form RealizarPagamento
     */
    public RealizarPagamento(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        efetuarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pagamentoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idCombo.addItem("Selecionar");
        for(String i: sys.idFuncionariosToStringArray()){
            idCombo.addItem(i);
        }
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });
        getContentPane().add(idCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 350, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 88, -1));

        efetuarButton.setText("Efetuar Pagamento");
        efetuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(efetuarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel2.setText("Valor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        pagamentoTxt.setEditable(false);
        getContentPane().add(pagamentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 350, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 500));

        setBounds(150, 70, 763, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if (idCombo.getItemAt(idCombo.getSelectedIndex()).equals("Selecionar")) {
            pagamentoTxt.setText("");
        } else {
            try {
                Funcionario fun = sys.buscarFuncionario(idCombo.getItemAt(idCombo.getSelectedIndex()));
                pagamentoTxt.setText(String.valueOf(fun.getPagamento()));

            } catch (FuncionarioInexistenteException e) {
            }
        }
    }//GEN-LAST:event_idComboActionPerformed

    private void efetuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarButtonActionPerformed
        try {
            Funcionario fun = sys.buscarFuncionario(idCombo.getItemAt(idCombo.getSelectedIndex()));
            sys.efetuarPagamento(fun.getPagamento());
            JOptionPane.showMessageDialog(this, "Pagamento realizado com sucesso!");
        } catch (PagamentoNaoAutorizadoException | FuncionarioInexistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_efetuarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton efetuarButton;
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pagamentoTxt;
    // End of variables declaration//GEN-END:variables
}
