package Views;

import Classes.SistemaLojaMusical;

/**
 *
 * @author gustavo
 */
public class RealizarPagamento extends javax.swing.JInternalFrame {
    SistemaLojaMusical sys;
    /**
     * Creates new form RealizarPagamento
     */
    public RealizarPagamento(SistemaLojaMusical sys) {
        this.sys = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idCombo.addItem("Selecionar");
        for(String i: sys.idFuncionariosToStringArray()){
            idCombo.addItem(i);
        }
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });
        getContentPane().add(idCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 350, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 88, -1));

        jButton1.setText("Efetuar pagamento");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel2.setText("Valor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 350, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-triangulos-livrit.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 500));

        setBounds(150, 70, 763, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if(idCombo.getItemAt(idCombo.getSelectedIndex()).equals("Selecionar")){
            nomeTxt.setText("");
            rgTxt.setText("");
            cpfTxt.setText("");
            telefoneTxt.setText("");
            salarioTxt.setText("");
        }else{
            try{
                Funcionario fun = sys.buscarFuncionario(idCombo.getItemAt(idCombo.getSelectedIndex()));
                nomeTxt.setText(fun.getNome());
                rgTxt.setText(fun.getRg());
                cpfTxt.setText(fun.getCpf());
                telefoneTxt.setText(fun.getTelefone().toString());
                salarioTxt.setText(String.valueOf(fun.getPagamento()));
            }catch (FuncionarioInexistenteException e){
            }
        }
    }//GEN-LAST:event_idComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
