package Views;

import Classes.*;
import Exceptions.InstrumentoJaExisteException;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class TelaInicial extends javax.swing.JFrame {
    public SistemaLojaMusical sys;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(SistemaLojaMusical sys) {
        this.sys = sys;
        try {
            sys.recuperar();
        } catch (Exception e){
            System.out.println("Criando arquivos pela primeira vez.");
            sys = new SistemaLojaMusical();
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lojaMenu = new javax.swing.JMenu();
        venderItem = new javax.swing.JMenuItem();
        sairItem = new javax.swing.JMenuItem();
        pessoaMenu = new javax.swing.JMenu();
        clientesSubMenu = new javax.swing.JMenu();
        cadClienteItem = new javax.swing.JMenuItem();
        removClienteItem = new javax.swing.JMenuItem();
        alteraClienteItem = new javax.swing.JMenuItem();
        listaClienteMenu = new javax.swing.JMenuItem();
        funcionariosSubMenu = new javax.swing.JMenu();
        cadFuncionarioItem = new javax.swing.JMenuItem();
        RemFuncionarioItem = new javax.swing.JMenuItem();
        AlteraFuncionarioItem = new javax.swing.JMenuItem();
        listaFuncionarioMenu = new javax.swing.JMenuItem();
        estoqueMenu = new javax.swing.JMenu();
        alteraInstrumentoItem = new javax.swing.JMenuItem();
        cadInstrumentoItem = new javax.swing.JMenuItem();
        removeInstrumentoItem = new javax.swing.JMenuItem();
        ListaInstrumentosItem = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        caixaItem = new javax.swing.JMenuItem();
        pagamentoMenu = new javax.swing.JMenuItem();
        sobreMenu = new javax.swing.JMenu();
        infoItem = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Folk's WAY");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPanePrincipal.setDesktopManager(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background Menor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jDesktopPanePrincipal.add(jLabel1);
        jLabel1.setBounds(0, -30, 1030, 730);

        lojaMenu.setText("Loja");

        venderItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        venderItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop-cart-icon.png"))); // NOI18N
        venderItem.setText("Vender Instrumento");
        venderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderItemActionPerformed(evt);
            }
        });
        lojaMenu.add(venderItem);

        sairItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sairItem.setText("Sair");
        sairItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairItemActionPerformed(evt);
            }
        });
        lojaMenu.add(sairItem);

        jMenuBar1.add(lojaMenu);

        pessoaMenu.setText("Pessoa");

        clientesSubMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clients-icon.png"))); // NOI18N
        clientesSubMenu.setText("Clientes");

        cadClienteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cadClienteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        cadClienteItem.setText("Cadastrar Cliente");
        cadClienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteItemActionPerformed(evt);
            }
        });
        clientesSubMenu.add(cadClienteItem);

        removClienteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        removClienteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/math-minus-icon.png"))); // NOI18N
        removClienteItem.setText("Remover Cliente");
        removClienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removClienteItemActionPerformed(evt);
            }
        });
        clientesSubMenu.add(removClienteItem);

        alteraClienteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        alteraClienteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist-icon.png"))); // NOI18N
        alteraClienteItem.setText("Alterar Cliente");
        alteraClienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraClienteItemActionPerformed(evt);
            }
        });
        clientesSubMenu.add(alteraClienteItem);

        listaClienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        listaClienteMenu.setText("Lista de Clientes");
        listaClienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClienteMenuActionPerformed(evt);
            }
        });
        clientesSubMenu.add(listaClienteMenu);

        pessoaMenu.add(clientesSubMenu);

        funcionariosSubMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/worker-brown-icon.png"))); // NOI18N
        funcionariosSubMenu.setText("Funcionario");

        cadFuncionarioItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        cadFuncionarioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        cadFuncionarioItem.setText("Cadastrar Funcionario");
        cadFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncionarioItemActionPerformed(evt);
            }
        });
        funcionariosSubMenu.add(cadFuncionarioItem);

        RemFuncionarioItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        RemFuncionarioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/math-minus-icon.png"))); // NOI18N
        RemFuncionarioItem.setText("Remover Funcionario");
        RemFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemFuncionarioItemActionPerformed(evt);
            }
        });
        funcionariosSubMenu.add(RemFuncionarioItem);

        AlteraFuncionarioItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        AlteraFuncionarioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist-icon.png"))); // NOI18N
        AlteraFuncionarioItem.setText("Alterar Funcionario");
        AlteraFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteraFuncionarioItemActionPerformed(evt);
            }
        });
        funcionariosSubMenu.add(AlteraFuncionarioItem);

        listaFuncionarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        listaFuncionarioMenu.setText("Lista de Funcionários");
        listaFuncionarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFuncionarioMenuActionPerformed(evt);
            }
        });
        funcionariosSubMenu.add(listaFuncionarioMenu);

        pessoaMenu.add(funcionariosSubMenu);

        jMenuBar1.add(pessoaMenu);

        estoqueMenu.setText("Estoque");

        alteraInstrumentoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        alteraInstrumentoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist-icon.png"))); // NOI18N
        alteraInstrumentoItem.setText("Alterar Instrumento");
        alteraInstrumentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraInstrumentoItemActionPerformed(evt);
            }
        });
        estoqueMenu.add(alteraInstrumentoItem);

        cadInstrumentoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        cadInstrumentoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        cadInstrumentoItem.setText("Cadastrar Instrumento");
        cadInstrumentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadInstrumentoItemActionPerformed(evt);
            }
        });
        estoqueMenu.add(cadInstrumentoItem);

        removeInstrumentoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        removeInstrumentoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/math-minus-icon.png"))); // NOI18N
        removeInstrumentoItem.setText("Remover Instrumento");
        removeInstrumentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInstrumentoItemActionPerformed(evt);
            }
        });
        estoqueMenu.add(removeInstrumentoItem);

        ListaInstrumentosItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        ListaInstrumentosItem.setText("Lista de Instrumentos");
        ListaInstrumentosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaInstrumentosItemActionPerformed(evt);
            }
        });
        estoqueMenu.add(ListaInstrumentosItem);

        jMenuBar1.add(estoqueMenu);

        adminMenu.setText("Administrativo");

        caixaItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        caixaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cash-register-icon.png"))); // NOI18N
        caixaItem.setText("Caixa Disponivel");
        caixaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaItemActionPerformed(evt);
            }
        });
        adminMenu.add(caixaItem);

        pagamentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cash-register-icon.png"))); // NOI18N
        pagamentoMenu.setText("Realizar Pagamento");
        pagamentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoMenuActionPerformed(evt);
            }
        });
        adminMenu.add(pagamentoMenu);

        jMenuBar1.add(adminMenu);

        sobreMenu.setText("Sobre");
        sobreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuActionPerformed(evt);
            }
        });

        infoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        infoItem.setText("Informações");
        infoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoItemActionPerformed(evt);
            }
        });
        sobreMenu.add(infoItem);

        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1019, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadClienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteItemActionPerformed
        CadastraCliente obj = new CadastraCliente(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cadClienteItemActionPerformed

    private void venderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderItemActionPerformed
        VenderInstrumento obj = new VenderInstrumento(this.sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_venderItemActionPerformed

    private void removClienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removClienteItemActionPerformed
        RemoveCliente obj = new RemoveCliente(this.sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_removClienteItemActionPerformed

    private void alteraClienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraClienteItemActionPerformed
        AlterarCliente obj = new AlterarCliente(this.sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_alteraClienteItemActionPerformed
        
    private void cadFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncionarioItemActionPerformed
        CadastraFuncionario obj = new CadastraFuncionario(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_cadFuncionarioItemActionPerformed

    private void RemFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemFuncionarioItemActionPerformed
        RemoveFuncionario obj = new RemoveFuncionario(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_RemFuncionarioItemActionPerformed

    private void AlteraFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteraFuncionarioItemActionPerformed
        AlterarFuncionario obj = new AlterarFuncionario(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_AlteraFuncionarioItemActionPerformed

    private void alteraInstrumentoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraInstrumentoItemActionPerformed
        AlterarInstrumento obj = new AlterarInstrumento(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_alteraInstrumentoItemActionPerformed

    private void cadInstrumentoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadInstrumentoItemActionPerformed
        CadastraInstrumento obj = new CadastraInstrumento(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_cadInstrumentoItemActionPerformed

    private void removeInstrumentoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInstrumentoItemActionPerformed
        RemoveInstrumento obj = new RemoveInstrumento(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_removeInstrumentoItemActionPerformed

    private void caixaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaItemActionPerformed
        CaixaDisponivel obj = new CaixaDisponivel(sys);
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_caixaItemActionPerformed

    private void sobreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_sobreMenuActionPerformed

    private void infoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoItemActionPerformed
        Sobre obj = new Sobre();
        jDesktopPanePrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_infoItemActionPerformed

    private void sairItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairItemActionPerformed
        try {
            this.sys.salvar();
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Poxa, deu erro ao fechar.");
        }
    }//GEN-LAST:event_sairItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            this.sys.salvar();
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Poxa, deu erro ao fechar.");
        }
    }//GEN-LAST:event_formWindowClosing

    private void ListaInstrumentosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaInstrumentosItemActionPerformed
         ListaDeInstrumentos obj = new ListaDeInstrumentos(sys);
         jDesktopPanePrincipal.add(obj);
         obj.setVisible(true);
    }//GEN-LAST:event_ListaInstrumentosItemActionPerformed

    private void listaClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClienteMenuActionPerformed
        ListaDeClientes obj = new ListaDeClientes(sys);
         jDesktopPanePrincipal.add(obj);
         obj.setVisible(true);
    }//GEN-LAST:event_listaClienteMenuActionPerformed

    private void listaFuncionarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFuncionarioMenuActionPerformed
        ListaDeFuncionarios obj = new ListaDeFuncionarios(sys);
         jDesktopPanePrincipal.add(obj);
         obj.setVisible(true);
    }//GEN-LAST:event_listaFuncionarioMenuActionPerformed

    private void pagamentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoMenuActionPerformed
        RealizarPagamento obj = new RealizarPagamento(sys);
         jDesktopPanePrincipal.add(obj);
         obj.setVisible(true);
    }//GEN-LAST:event_pagamentoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SistemaLojaMusical sys = new SistemaLojaMusical();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial(sys).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlteraFuncionarioItem;
    private javax.swing.JMenuItem ListaInstrumentosItem;
    private javax.swing.JMenuItem RemFuncionarioItem;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuItem alteraClienteItem;
    private javax.swing.JMenuItem alteraInstrumentoItem;
    private javax.swing.JMenuItem cadClienteItem;
    private javax.swing.JMenuItem cadFuncionarioItem;
    private javax.swing.JMenuItem cadInstrumentoItem;
    private javax.swing.JMenuItem caixaItem;
    private javax.swing.JMenu clientesSubMenu;
    private javax.swing.JMenu estoqueMenu;
    private javax.swing.JMenu funcionariosSubMenu;
    private javax.swing.JMenuItem infoItem;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listaClienteMenu;
    private javax.swing.JMenuItem listaFuncionarioMenu;
    private javax.swing.JMenu lojaMenu;
    private javax.swing.JMenuItem pagamentoMenu;
    private javax.swing.JMenu pessoaMenu;
    private javax.swing.JMenuItem removClienteItem;
    private javax.swing.JMenuItem removeInstrumentoItem;
    private javax.swing.JMenuItem sairItem;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JMenuItem venderItem;
    // End of variables declaration//GEN-END:variables
}
